theme: jekyll-shell-theme
title: Xander Allen's Homepage
description: I'm a current student at IU Bloomington studying Computer Science in the Luddy School of Informatics, 
Computing, and Engineering. I developed a passion for CS during high school when I built my first PC and realized 
just how powerful of a tool I had access to. Since then, I have studied programming languages such as Java, Python, 
and C++ along with topics in Data Structures and Algorithms and Database Management. I have an especially strong 
passion for Game Development and Machine Learning.
